name: Increment version number and export

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo "$(expr $(cat version) + 1)" > version

      - run: echo "{\"pack\":{\"pack_format\":8,\"description\":[\"\",{\"text\":\"Horizon's End\",\"color\":\"#88FF88\"},\" Resource Pack\",\"\nVersion $(cat version) \",{\"text\":\"//\",\"color\":\"#222222\"},\" horizonsend.net\"]}}" > pack.mcmeta

      - uses: EndBug/add-and-commit@v8.0.2
        with:
          message: Increment version number.
          
      - run: zip -r HorizonsEndResourcePack.zip *

      - run: export VERSION=$(cat version)

      - uses: ncipollo/release-action@v1.10.0
        with: 
          artifacts: HorizonsEndResourcePack.zip
          tag: Version${{ env.VERSION }}
